### PR TITLE
Test library with PHP 7.4

### PR DESCRIPTION
**Pull request by markuspoerschke**

### CODE REVIEW

**Comment by peter279k** [comment]
The `php-7.4` version is unstable.

If we want to use this preview version, I think we can use the ` - "7.4snapshot"` in `.travis.yml`.

The useful references are as follows:

- [PHPCompatibility/PHPCompatibility](https://github.com/PHPCompatibility/PHPCompatibility/blob/master/.travis.yml#L20)
- [php-7.4 status in Travis](https://twitter.com/nikita_ppv/status/1094897743594770433)
- [Add PHP 7.4 branch to test against](https://travis-ci.community/t/add-php-7-4-branch-to-test-against/2179)

**Comment by peter279k** [comment]
@markuspoerschke, the latest Travis CI build because of the `php-cs-fixer`.

The `php-xs-fixer` doesn't recognize the `php-7.4-dev` version.

**Comment by peter279k** [comment]
I think we can add the condition in Travis CI build setting:

If the PHP version is `7.4-dev`, stopping the code coverage generation and coding style check.

**Comment by ankurk91** [comment]
Php 7.4 stable is available on travis ci now

**Pull request merged**
