### PR TITLE
preventing mutation of end date various times

### PR DESCRIPTION
**Pull request by piyushkantm**
Addressing the issue which is adding day to the end date more than once.

https://github.com/markuspoerschke/iCal/issues/98

### CODE REVIEW

**Comment by piyushkantm** [comment]
By the way Referencing from https://github.com/markuspoerschke/iCal/pull/83

> All day events should always end the next day. Additionally the tzid should not be applied to all day events.

Shouldn't it be 

>If end date is not set by the user then:
 `$this->dtEnd = (clone $this->dtStart)->add(new \DateInterval('P1D'));`
If user has set the end date then leave it as is?

**Comment by markuspoerschke** [comment]
> By the way Referencing from #83

>>    All day events should always end the next day. Additionally the tzid should not be applied to all day events.

> Shouldn't it be

>> If end date is not set by the user then:
>>  ```$this->dtEnd = (clone $this->dtStart)->add(new \DateInterval('P1D'));```
>> If user has set the end date then leave it as is?

Actually that might be true. But I did not heart of any ical client interpreting this wrongly. A missing ` `DTEND` should automatically indicate a single day event. If you expirience any problems please feel free to create another PR.

**Comment by markuspoerschke** [comment]
@piyushkantm Thanks for your PR. 

Since #99 was nearly covering the same issue I was updating that one to also contain this fix.

**Comment by piyushkantm** [comment]
> But I did not heart of any ical client interpreting this wrongly.

Yes you are right. If we implement this, it would mess with the endDate or Duration logic we currently have. 👍

**Comment by markuspoerschke** [comment]
Available in Version [0.12.1](https://github.com/markuspoerschke/iCal/releases/tag/0.12.1) now.

**Pull request closed without merging**
