### PR TITLE
Allow new lines in event descriptions

### PR DESCRIPTION
**Pull request by jrjohnson**
I'm pretty sure that description is allowed to contain new lines:
https://tools.ietf.org/html/rfc5545#page-85

I took at pass at implementing this, but I'm happy to do it a different way.

### CODE REVIEW

**Comment by jrjohnson** [comment]
@markuspoerschke anything I need to do to get this merged?  Scrutinizer just says  Canceled, I don't see a way to run it again or get any error output.

**Comment by jrjohnson** [comment]
@markuspoerschke friendly reminder.  Can I make any changes to get this merged?

**Comment by markuspoerschke** [comment]
Hey,

thanks for your changes!

I will merge it now. Sorry for the delay!

Cheers
Markus

**Comment by jrjohnson** [comment]
Great and thanks for the quick release as well!  Love the library, saved me at least a month of work.

**Comment by dlubitz** [comment]
Hey guys. Sorry, but this PR breaks the possibility of line breaks in the description.
See RFC: http://www.ietf.org/rfc/rfc2445.txt Page 81

> Example: The following is an example of the property with formatted
   line breaks in the property value:

     DESCRIPTION:Meeting to provide technical review for "Phoenix"
       design.\n Happy Face Conference Room. Phoenix design team
       MUST attend this meeting.\n RSVP to team leader.

So the line breaks "\n" have to replaced with the string '\\n' as it was before this change. In version 0.8.0 everything works as expected with linebreaks in the description.

**Comment by jrjohnson** [comment]
@dlubitz That isn't how I read the RFC, but I'm completely willing to be wrong.  I read it as "formatted
line breaks" meaning real line breaks and not line break '\n' characters in the string.  Seems a bit unclear, but maybe I'm just bad at reading RFCs.

**Comment by dlubitz** [comment]
@jrjohnson: I think the section 4.3.11 "Text" makes it more clear.
> ESCAPED-CHAR = "\\" / "\;" / "\," / "\N" / "\n")
>        ; \\ encodes \, \N or \n encodes newline
...

> An intentional formatted text line break MUST only be included in a
   "TEXT" property value by representing the line break with the
   character sequence of BACKSLASH (US-ASCII decimal 92), followed by a
   LATIN SMALL LETTER N (US-ASCII decimal 110) or a LATIN CAPITAL LETTER
   N (US-ASCII decimal 78), that is "\n" or "\N".

**Pull request merged**
