### PR TITLE
Optimize Performance for long lines

### PR DESCRIPTION
**Pull request by stchr**
use mb_strcut() instead of preg_split()

### CODE REVIEW

**Comment by stchr** [comment]
Is there anything I can do to push this PR?
It is an massive improvement both CPU and memory usage. Here a quick and dirty test with 1000 calls of 
```php
for ($i = 0; $i < 1000; $i++) {
    Eluceo\iCal\Util\ComponentUtil::fold('Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.');
}
```

Before:

Function|Call Count|Self Wall Time|Self CPU|Self MemoryUsage|Inclusive Wall Time|Inclusive CPU|Inclusive Memory Usage
--------|----------|--------------|--------|----------------|-------------------|-------------|----------------------
Eluceo\iCal\Util\ComponentUtil::fold|1000|1,863,972 µs|921,875 µs|-60,887,248 bytes|2,121,698 µs|2,125,000 µs|2,752 bytes
preg_split|1000|221,425 µs|921,875 µs|60,889,544 bytes|221,425 µs|250,000 µs|60,889,544 bytes
strlen|1182000|36,301 µs|921,875 µs|456 bytes|36,301 µs|953,125 µs|456 bytes

After:

Function|Call Count|Self Wall Time|Self CPU|Self MemoryUsage|Inclusive Wall Time|Inclusive CPU|Inclusive Memory Usage
--------|----------|--------------|--------|----------------|-------------------|-------------|----------------------
Eluceo\iCal\Util\ComponentUtil::fold|1000|57,037 µs|46,875 µs|-2,863,024 bytes|87,592 µs|93,750 µs|93,750 µs
mb_strcut|14000|29,701 µs|46,875 µs|2,864,456 bytes|29,701 µs|46,875 µs|2,864,456 bytes

It is nearly 25 times faster and uses 25 times less memory for this simple example. Even a fallback to the old implementation if multibyte extension is not installed is provided.

**Comment by markuspoerschke** [comment]
Hallo @stchr,

thanks for your contribution. Looks good. I tested the output and it was the same.

I also tested the performance using [PHPench](https://github.com/mre/PHPench). This is how it looks to me:

image

```
<?php

require_once __DIR__ . '/../vendor/autoload.php';

abstract class AbstractBenchmark implements \mre\PHPench\BenchmarkInterface
{
    protected $i = 1;
    protected $text = 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.';

    function setUp($i)
    {
        $this->i = $i;
    }

    public function execute()
    {
        for ($i = 0; $i < $this->i; $i++) {
            $this->fold($this->text);
        }
    }

    abstract protected function fold($string);
}

class BenchmarkPregSplitStrLen extends AbstractBenchmark
{

    protected function fold($string)
    {
        $lines = array();
        $array = preg_split('/(?<!^)(?!$)/u', $string);
        $line = '';
        $lineNo = 0;
        foreach ($array as $char) {
            $charLen = strlen($char);
            $lineLen = strlen($line);
            if ($lineLen + $charLen > 75) {
                $line = ' ' . $char;
                ++$lineNo;
            } else {
                $line .= $char;
            }
            $lines[$lineNo] = $line;
        }
    }
}

class BenchmarkMbStrcut extends AbstractBenchmark
{
    protected function fold($string)
    {
        $lines = [];
        while (strlen($string) > 0) {
            if (strlen($string) > 75) {
                $lines[] = mb_strcut($string, 0, 75, 'utf-8');
                $string = ' ' . mb_strcut($string, 75, strlen($string), 'utf-8');
            } else {
                $lines[] = $string;
                $string = '';
                break;
            }
        }
    }
}

// Create a new benchmark instance
$phpench = new mre\PHPench(new \mre\PHPench\Aggregator\MedianAggregator);

$output = new \mre\PHPench\Output\GnuPlotOutput('ical_fold.png', 1024, 768);
$output->setTitle('Compare fold with preg_split and strln vs. mb_strcut');
$phpench->setOutput($output);


// Add your test to the instance
$phpench->addBenchmark(new BenchmarkPregSplitStrLen, 'preg_split + strlen');
$phpench->addBenchmark(new BenchmarkMbStrcut, 'mb_strcut');

// Run the benchmark and plot the results in realtime.
// With the second parameter you can specify
// the start, end and step for each call
$phpench->setInput(range(1, pow(2, 12), 512));
$phpench->setRepetitions(4);
$phpench->run(true);
```

It is really a very good performance improvement! Thanks for that.

I will merge the changes now. Thanks for your contribution! Very good catch! Looks like you are generating a lot of iCal files? 😄 

Viele Grüße
Markus

**Comment by markuspoerschke** [comment]
The change was released in `0.11.4`! 🍻

**Comment by stchr** [comment]
Thanks! Didn't know PHPench.
And yes, I'm generating large iCal subscriptions with a lot of VEVENT items 👏

**Pull request merged**
