### PR TITLE
RecurrenceRule now also allows hourly, minutely and secondly frequencies

### PR DESCRIPTION
**Pull request by SHyx0rmZ**

### CODE REVIEW

**Comment by SHyx0rmZ** [comment]
@markuspoerschke Any idea when you can get around to this?

**Comment by markuspoerschke** [comment]
Nice! Thanks a lot!

**Comment by markuspoerschke** [comment]
Released with `0.11.0`.

**Comment by SHyx0rmZ** [comment]
Thank you very much 🎉

**Pull request merged**
