### PR TITLE
Revert "Merge pull request #53 from jrjohnson/newline-description"

### PR DESCRIPTION
**Pull request by buergimi**
This reverts commit 340c6345deb6ff3758333c9fdb6b3d60661fc184, reversing
changes made to 6ad1850daed537d703dadaf38a701cfaaca0704e.

the reverted commit did not fix multi-line descriptions, it broke it. When I remove this commit completely, multi-line descriptions work just fine.

### CODE REVIEW

**Comment by navarr** [comment]
Sounds like a test is needed.

**Comment by markuspoerschke** [comment]
I think this will be fixed with #60?

**Comment by buergimi** [comment]
Yes, bug is fixed with #60. But you still have the following issues:

* You still have the obsolete property "Description" which is identical to "StringValue"
* You still have the method escapeValueAllowNewLine() which is not used any more

Since you already merged #60, you can close my pull request. But I'd recommend fixing the two minor issues above.

**Comment by markuspoerschke** [comment]
@buergimi Thanks for your input. I fixed the issues you mentioned! 😃

**Pull request closed without merging**
