### PR TITLE
Add BYSETPOS to RecurrenceRule

### PR DESCRIPTION
**Pull request by theeternalsw0rd**
Reformatted some code to match style. Hopefully travis build passes now.

### CODE REVIEW

**Comment by theeternalsw0rd** [comment]
Sorry for the clutter. Should have left original pull request in place. Didn't realize github would automatically update. Here's what I put in the initial pull request description:

Adds BYSETPOS with proper input validation. Can accept null|int|string|array. Other methods seem to throw on valid input. For example BYMONTH is a csv string in the spec, but the set method only accepts a single integer. I figured I should save refactoring for another pull request.

**Comment by wendelin** [comment]
I need BYSETPOS.
Is there any chance of this getting merged anytime soon?

**Comment by markuspoerschke** [comment]
Looks good, thanks!

**Comment by markuspoerschke** [comment]
Thanks for your contribution! This change will be available in [0.15.0](https://github.com/markuspoerschke/iCal/releases/tag/0.15.0)!

**Pull request merged**
