### PR TITLE
declare getProperties method protected to open it for extension

### PR DESCRIPTION
**Pull request by vazaha-nl**
This change makes it possible to subclass the CalendarFactory and extend the getProperties method, for example to add custom calendar properties. See #383

### CODE REVIEW

**Comment by markuspoerschke** [comment]
Thanks for your contribution. Especially for the detailed description! 👍🏻 

Can you add a new section to the changelog? Then I will merge it.

**Comment by vazaha-nl** [comment]
I updated the changelog.

**Comment by westy92** [comment]
@markuspoerschke any chance this can get merged and released? Thanks!

**Comment by vazaha-nl** [comment]
@markuspoerschke 

I am actually needing this change for another project but I'd rather not duplicate code again nor use a forked version.

Can you please merge this PR? I already fixed the merge conflict by merging in the 2.x branch. 

Thanks a lot!

**Comment by vazaha-nl** [comment]
@markuspoerschke is there any reason you don't want to merge this PR? I noticed there's been a new release just a few hours ago, it would have been so great if this change was included in that release....

**Comment by markuspoerschke** [comment]
@vazaha-nl Sorry for the delay. I am only working spare time on this project, that is why I am sometimes responding slow. 

Change looks good, I will merge & release it.

**Pull request merged**
