### PR TITLE
Allow multiple recurrence rules in an event

### PR DESCRIPTION
**Pull request by SHyx0rmZ**

### CODE REVIEW

**Comment by markuspoerschke** [comment]
Thanks for your PR!

**Comment by markuspoerschke** [comment]
Released with `0.11.0`.

**Comment by markuspoerschke** [comment]
I checked the changes in this PR again. According to the RFC 5545 the `RRULE` property should not be specified more than once:

> This property [RRULE property] can be specified in recurring "VEVENT",
      "VTODO", and "VJOURNAL" calendar components as well as in the
      "STANDARD" and "DAYLIGHT" sub-components of the "VTIMEZONE"
      calendar component, but it SHOULD NOT be specified more than once.
      The recurrence set generated with multiple "RRULE" properties is
      undefined.

Therefore it should only be possible to define it once within the implementation of this library.

Currently the implementation is broken because the `PropertyBag` was changed to accept only one property with the same name. `Fatal error: Uncaught Exception: Property with name 'RRULE' already exists in /var/www/html/vendor/eluceo/ical/src/PropertyBag.php:65`.

@SHyx0rmZ Do you have an use case for adding more than one recurrence rule? Because I tend to revert the changes from this PR again so that only one recurrence rule per component is allowed.

**Comment by SHyx0rmZ** [comment]
@markuspoerschke I use this to do evil things like representing a recurrence every two days and five minutes. Reverting the changes seems like the sane thing to do, I must've overlooked that bit in the RFC when I read it. My use case should be covered by me calculating a bigger interval for the smallest frequency I can find, or so I thought until I saw that the interval is only allowed to be a single digit just now. I'll probably just scrap the calendar export functionality altogether, as I don't know anyone who uses it. Conclusion: Trying to cram your Cron job schedules into a calendar isn't a very good idea.

**Pull request merged**
